### ISSUE TITLE
Bug: spotted InterpolatedParameter overshoot if it has to deal with a large amount of steps (potentially *very* dangerous)

### ISSUE THREAD

**Issue by visualizersdotnl** [bipolaraudio/FM-BISON#144]

**Comment by visualizersdotnl** [comment]
Please fix by inserting clamp into implementation itself.

**Comment by paulcoops** [comment]
I've had aftertouch, supersaw mix and supersaw detune overshoot with Morph.

**Comment by visualizersdotnl** [comment]
This was to be expected, adding floating point values never adds up to the exact maximum or minimum. I'll have to fix this posthaste.

**Comment by visualizersdotnl** [comment]
Quick non-fix: double precision as internal type for juce::SmoothedValue..

**Comment by visualizersdotnl** [comment]
HIGH priority now!

**Comment by visualizersdotnl** [comment]
@paulcoops Idea: we supply a min. and max. to each InterpolatedParameter instance and clamp the output.

**Comment by visualizersdotnl** [comment]
`        auto clampedValue = jlimit (static_cast<ValueType> (0), static_cast<ValueType> (1), value);
`

**Comment by visualizersdotnl** [comment]
```
const float result = m_value.getNextValue();
return (clamp) ? jlimit<float>(minimum, maximum, result) : result;

```

Now I need to review all instances of InterpolatedParameter.

**Comment by visualizersdotnl** [comment]
@paulcoops Should be fixed now. Pushed. Please re-open if not; if you encounter any range bugs it's probably because I've set it up wrong; correct them accordingly. But I tried to be careful :-)
