### ISSUE TITLE
Feature for new UI: get operator waveforms & RMS/peak

### ISSUE THREAD

**Issue by paulcoops** [bipolaraudio/FM-BISON#222]
Goal: stereo VU meters in operator list. 
Request: could GetOperatorPeak() (exposed in FM_BISON.h) return an array of floats: RMSL and RMSR? 

Will use the first for left & modulator and second for right if isCarrier.

(sorry, corrected, OCD)

**Comment by visualizersdotnl** [comment]
It's not the peaks or the RMS we're after, we just want the raw waveforms of each "unprocessed" operator for the amount of samples that have been rendered (which is variable, or at least, it depends on your settings and then depending on DAW et cetera it can vary - so it might be a good idea to update the render by either waiting until you have a fixed amount of samples or you scroll.

I'll take care of this at some point in time, soon-ish.

**Comment by visualizersdotnl** [comment]
I'm not sure why I wrote the above; we want both the waveform and possibly the peaks (though you could argue that implementing a working VU meter is something that should be done/handled plug-in side). Will look into it after we've fixed more important bugs in the audio rendering itself!

**Comment by paulcoops** [comment]
This is currently low priority. However, when we implement this, we need to make sure this is thread safe. 

If i remember correctly the idea behind the waveform was to pre-render and plot a couple of phases of the operator's waveform as an icon. We'll discuss this when we need it.

**Comment by visualizersdotnl** [comment]
I'm closing this ticket. We can resurrect this one or open a new one if we eventually need something like this.
