### ISSUE TITLE
Compressor: larger compression (ratios) range?

### ISSUE THREAD

**Issue by visualizersdotnl** [bipolaraudio/FM-BISON#228]
@paulcoops I often catch you slidin' it all the way to 1:20, do we need to be either more precise or supply more range or both?

**Comment by visualizersdotnl** [comment]
Shoulnd't be necessary..

Source: https://youtu.be/O3GQi7q3ZLg

**Comment by visualizersdotnl** [comment]
I'll check wat Reaper's does, though that is by no means always a sensible number, remember the 250MS lookahead?

**Comment by paulcoops** [comment]
Yeah, I sometimes do like extreme compression. Ableton's compressor goes all the way to Inf. Check its flatenator preset on a short sound with a long reverb.

**Comment by visualizersdotnl** [comment]
@paulcoops Still relevant?

**Comment by paulcoops** [comment]
Well, I still crank it up to 20 for the max settings in morph. Not sure how much difference it actually makes. But personally I want to be able to crank it all the way up and down.

**Comment by visualizersdotnl** [comment]
"What is a good compression ratio for audio?
A ratio of around 3:1 is considered moderate compression, 5:1 would be medium compression, 8:1 starts getting into strong compression and 20:1 thru ∞:1 (infinity to one) would be considered “limiting” by most, and can be used to ensure that a signal does not exceed the amplitude of the threshold."

Now, we have 20, so I'm closing this ticket. If you want more, look up the max. in synth-global.h and change it :)
