### ISSUE TITLE
Improve distortion ('screamer') effect to pedal quality

### ISSUE THREAD

**Issue by visualizersdotnl** [bipolaraudio/FM-BISON#232]

**Comment by visualizersdotnl** [comment]
Ideas:
- Envelope follower (see example .ALS)
- EQ
- ...

**Comment by visualizersdotnl** [comment]
Filter at some stage too? Discuss with @paulcoops - I really need to take some time off for this project soon.

**Comment by visualizersdotnl** [comment]
Agreeing with @paulcoops it might make a lot more sense if we move the distortion pass up the chain so it sits *before* the 24dB filter. Will test ASAP.

**Comment by visualizersdotnl** [comment]
"so maybe: signal -> envelope (attack & release) -> EQ -> distort -> wet/dry mix"

**Comment by visualizersdotnl** [comment]
Submitted moving the 24dB filter to be applied *after* distortion. This is a step in the right direction.

**Comment by paulcoops** [comment]
Now we can't use the distortion without the 24dB ladder filter. Not a bad thing for the patches we're working on now. 

What about: signal -> envelope (attack & release) -> distort -> 12db or 24db low pass -> wet/dry mix"

**Comment by visualizersdotnl** [comment]
I'd offer: signal -> compressor -> distort -> low pass -> wet/dry?

**Comment by visualizersdotnl** [comment]
Current setup (signal -> filter -> distort (incl. drive/asymmetry) -> DC blocker) sounds kind of sweet. I'd like to add the option to modify the tone in more than 1 way (variable Q).

**Comment by visualizersdotnl** [comment]
It's now roughly equivalent to the basic BOSS distortion pedal.
