### ISSUE TITLE
Problem with supersaw oscillator, reported by Paul

### ISSUE THREAD

**Issue by visualizersdotnl** [bipolaraudio/FM-BISON#234]
@paulcoops It's been a while since we've touched the engine, I blame the job, but can you describe here what exactly is wrong with it so I can tend to it?

**Comment by paulcoops** [comment]
Okay, so there seems to be an issue with pitch changes and the (sub)oscillator phase. When invoking a pitch-bend, monophonic glide or pitch-lfo; an audible pop can be heard (especially when low-passed). Looking at the waveform it looks like a phase is being reset when a pitch-change occurs. 
![fmbsupersaw_pitch](https://user-images.githubusercontent.com/6607599/117484817-e4cc0400-af67-11eb-8fd5-7f5395887dcf.png)

**Comment by visualizersdotnl** [comment]
@paulcoops Fixed, please test.

**Comment by visualizersdotnl** [comment]
Problem solved.
