### ISSUE TITLE
Bug: distortion can easily "blow up" 24dB ladder filter, swap them, or? -> Does this still happen after recent panning fix?

### ISSUE THREAD

**Issue by visualizersdotnl** [bipolaraudio/FM-BISON#239]
@paulcoops What's your take on this problem?

**Comment by paulcoops** [comment]
I think the problem is most noticeable in polyphonic mode where multiple notes add to the amplitude of the signal. A simple fix could be to move the 24dB filter behind the compressor. Another idea is to lower the minimum value of the drive parameter.

**Comment by visualizersdotnl** [comment]
Let's see if this is still the case and if we may want to swap the order to begin with.

**Comment by visualizersdotnl** [comment]
This shouldn't happen again. Sure, that's a bit of a guesstimate, but I'm quite certain of it. And if it does, we'll reopen it.
