### ISSUE TITLE
Monophonic glide and MIDI precision

### ISSUE THREAD

**Issue by paulcoops** [bipolaraudio/FM-BISON#246]
Currently, to start a new voice, there must be a space between notes. If this space is too small, (sometimes) no new voice will start and you will get a glide. This is a problem in production.

Ideally, when a note-on and note-off have the same timestamp, the note-off should be processed first. So that if the notes are on a grid in the DAW, glide only occurs when notes overlap.  I remember we discussed using timestamps a while ago, and it might be a solution.

**Comment by visualizersdotnl** [comment]
Yes, I see the problem. So if I read you correctly, in this case I should check if -- in monophonic mode -- if there are duplicate time stamps and if so, prioritize them differently. This should be a relatively easy fix. Will look into it next week (vacation!).

**Comment by visualizersdotnl** [comment]
OK, I've got this running using Ableton and my build of the R&D, 2 things:
- Always keep track of *all* request, even though you honour only the relevant (latest?)
- Same goes for release
- NOTE_ON and NOTE_OFF at the same time is a special case (if you can't wrap that any nicer)

**Comment by visualizersdotnl** [comment]
Fixed!
