### ISSUE TITLE
Design & implement our own envelope type and replace Redmon's analogue type envelope

### ISSUE THREAD

**Issue by visualizersdotnl** [bipolaraudio/FM-BISON#254]

**Comment by visualizersdotnl** [comment]
@paulcoops Sketches, ideas: here please :-)

We're planning to do this in a new branch of the engine.

**Comment by paulcoops** [comment]
What about using [Cubic Bézier Curves ](https://en.wikipedia.org/wiki/B%C3%A9zier_curve#Cubic_B%C3%A9zier_curves)for the **Attack** **Decay** and **Release** phase.

[Check the sketch](https://github.com/bipolaraudio/FM-BISON-internal-plug-in/issues/50)

It introduces a new parameter group per envelope curve containing:

- pointA (float, float) 0..1
- pointB (float, float) 0..1
- duration (float) 0..30s?
- easeOut (bool)*

The start and end points for the Cubic Bézier Curve are derived from the easyOut bool. 
_*I don't think we want this to be an automatable parameter. Attack is always an ease-in, so we can decide to hardcode this value for the type of envelope on both UI and Engine side._

**Sustain** uses a level (float) which is basically the decay curve's, endpoint's y value.

Optionally, we can add a decay rate on the sustain, perhaps ranging from -1..1, so you can have a sustain phase that gets softer or louder over time.

**Comment by visualizersdotnl** [comment]
I've just replaced the convoluted ADSR for a customized copy of Juce's ADSR class. It's a good place to start.

**Comment by visualizersdotnl** [comment]
Submitted. That decay on sustain is implemented to simulate piano pedal mode by the way.

**Comment by visualizersdotnl** [comment]
Must fix skipping of attack phase when 'piano pedal mode' enabled.

**Comment by paulcoops** [comment]
I ended up using a cubic curve where the control points are calculated from a single value. Visualization of the same curve is in the beta branch of the R&D plugin.

**Comment by visualizersdotnl** [comment]
Looks and works fine. Tight code too. Closing this issue!
