### ISSUE TITLE
Are we loud enough 'by default'? (includes 'low cut' issue(s))

### ISSUE THREAD

**Issue by visualizersdotnl** [bipolaraudio/FM-BISON#255]

**Comment by paulcoops** [comment]
For patch design in general we can follow this rule of thumb: 

> "...synths or pads at somewhere between -20 and -16 dBFS, with transient peaks (such as occur from drums and percussive instruments) no higher than -6 dBFS". 

I think the standard 'single sinus patch' should be at the lower end of this range. So that we leave enough headroom for adding operators.

**Comment by visualizersdotnl** [comment]
I've tweaked the low cut a little and we're not sounding like a tin can anymore but it might not be 100% yet.

**Comment by visualizersdotnl** [comment]
Also, low passing a voice shut doesn't kill it. It should.

**Comment by visualizersdotnl** [comment]
^^ This has been fixed. Going to look at our default output now and tweak so that you start out with a clean slate that hovers somewhere around -16.

**Comment by visualizersdotnl** [comment]
Initializing the master volume at -12dB settles the sine at -16 - I think this will do for now.
