### ISSUE TITLE
Reverb: dry/wet is wrong, reverb should *add* with a *drive*

### ISSUE THREAD

**Issue by visualizersdotnl** [bipolaraudio/FM-BISON#259]

**Comment by visualizersdotnl** [comment]
Or maybe not?

**Comment by paulcoops** [comment]
I would not change it for now. It depends on the kind of effect you want. And if we limit it to add, you can't create a far away sound anymore. However, if effects can use different blend modes; that could be very interesting.

**Comment by visualizersdotnl** [comment]
Point accepted :) 

Closing ticket for now.
