### ISSUE TITLE
Static processing buffers cause engine crash

### ISSUE THREAD

**Issue by paulcoops** [bipolaraudio/FM-BISON#260]
So I've had this happening (very rarely) when adding an instrument in Live. renoise and FL Studio:
![afbeelding](https://user-images.githubusercontent.com/6607599/131901016-158dda7a-a52e-4f20-8ee0-2e4da64d2696.png)

juce says: 
```
Note that if the buffer is resized or its number of channels is changed, it will re-allocate memory internally 
and copy the existing data to this new area, so it will then stop directly addressing this memory.

Parameters
dataToReferTo a pre-allocated array containing pointers to the data for each channel that should be used by this buffer. 
The buffer will only refer to this memory, it won't try to delete it when the buffer is deleted or resized.
```

**Comment by visualizersdotnl** [comment]
Yeah, I was afraid that this would pop up sooner or later :)

**Comment by visualizersdotnl** [comment]
This really should not happen, plus we eliminated the "ParameterSlew" disaster.

**Comment by visualizersdotnl** [comment]
Closing because: should not happen. Certainly not when offending assertion(s) removed from plug-in processor.
