### ISSUE TITLE
Monophonic pedal behaviour

### ISSUE THREAD

**Issue by paulcoops** [bipolaraudio/FM-BISON#264]
When in monophonic mode and holding the sustain pedal down a new voice gets triggered on key down. Ableton's operator has the same behavior. https://github.com/bipolaraudio/Morph/issues/34

**Comment by visualizersdotnl** [comment]
"When in monophonic mode and holding the sustain pedal down a new voice gets triggered on key down. Ableton's operator has the same behavior."

That makes sense. I'm keeping the sustain boolean separately from the key allocation system so it will probably be in the 'veronderstelling' that it can go ahead and play a new note.

Do we want to change this @paulcoops ?

**Comment by paulcoops** [comment]
No, I don't think so. We changed it a while back so *only overlapping notes glide*, and I'm happy with that.
