### ISSUE TITLE
Compressor causes inadvertent delay (attack? delay line?) when rendering.

### ISSUE THREAD

**Issue by visualizersdotnl** [bipolaraudio/FM-BISON#265]

**Comment by visualizersdotnl** [comment]
We're debugging (with @paulcoops ) - testing if the problem is the eventual gain the output is multiplied with or not..

**Comment by visualizersdotnl** [comment]
I've checked in a temporary fix (resembling the code that feeds the "gain dB envelope" attack and release) but I'm still at a loss as to why it behaves that way.

**Comment by visualizersdotnl** [comment]
Should be fixed; please verify @paulcoops

**Comment by paulcoops** [comment]
Confirmed! The kInfdB transition was the culprit.
