### ISSUE TITLE
There's a bug (probably related to main delay effect) where the signal just builds up to INF: investigate!

### ISSUE THREAD

**Issue by visualizersdotnl** [bipolaraudio/FM-BISON#82]

**Comment by visualizersdotnl** [comment]
Should be fixed; I simply forgot to leak a little.

**Comment by visualizersdotnl** [comment]
@paulcoops - I'll need a .RPP example some time. No hurry.

**Comment by paulcoops** [comment]
Try FM-BISON 0.9 demo (WIP).rpp. play the demo, stop at the end. wait for 30-60 seconds and watch how channel 9 Engine Pad, slowly build's up a signal till auto mute.

**Comment by visualizersdotnl** [comment]
OK, will check when I return to work in a few days.

**Comment by paulcoops** [comment]
The issue with the demo doesn't seem to be related to the delay line. Changing the delay feedbacks here makes no difference and the dry signal seems to already contain the self-oscillation effect.

**Comment by visualizersdotnl** [comment]
I'll have a look tonight or tomorrow to figure out what's going on.

**Comment by visualizersdotnl** [comment]
The SVF filter never reaches true zero, which I should look into, but for now I replaced it for the 6dB single pole filter, which does not have that problem as a simple first order IIR.

**Comment by visualizersdotnl** [comment]
I've also modified the delay to have a *way* longer feedback, so this might need some fixing of patches (especially the 0.9 demo, @paulcoops ).

**Comment by visualizersdotnl** [comment]
Fixed.
