### ISSUE TITLE
Add: LFO polarity switch (negative, bipolar, positive)

### ISSUE THREAD

**Issue by visualizersdotnl** [bipolaraudio/FM-BISON#86]
Could be a cool moment to add some little icons as well.

**Comment by paulcoops** [comment]
Is this a switch like a combo-box, or a slider/rotary with a floating value? -1 negative, 0 bipolar, 1 positive?

**Comment by visualizersdotnl** [comment]
<img width="643" alt="LFO positive" src="https://user-images.githubusercontent.com/1901569/83505756-87614480-a4c6-11ea-8f2e-a8a051122a76.PNG">

See image. A toggle switch of sorts (with 3 positions) would be preferable. One (mid./center or 'bipolar' - we really should just use images to visualize this in the GUI) keeps the LFO value range within -1 to 1 as it is right now, where as positive scales it by half and lifts it up (only positive values) and negative does the same and inverts the wave so it's the exact opposite of positive.

And while we're at it, at some point I will take some time to rename the 'Bias' parameter to 'Blend'; seems more user-friendly and self-explanatory.

**Comment by paulcoops** [comment]
Okay, I think a combo-box is currently the best UI element for this. Toggles currently look like switches. A radio-button style toggle would give a more expect behavior, but we would have to build that style, and it would take up more space. The downside of using a combo-box is that icons are currently not supported out of the box by JUCE. But if we figure out a way to add icons to a combo-box, maybe I can extend the inter font with icons, we can use it on more places (sine, saw, lowpass, etc.)

**Comment by visualizersdotnl** [comment]
So, a few things:
* What do you mean by "a more expect behavior"?
* I can get onboard with the combobox idea, though I don't think it's ideal.
* This part of the issue belongs in the VST project (my bad, and I'll correct it).
* I'll have a closer look if we can find something more suitable; don't forget I can alter component state in code quite easily so the option to "sculpt" something out of multiple out-of-the-box components is always an option.

Let us continue this discussion later on; let it rest for a bit, as we've got other priorities to tend to. Or at least I do :)

I'll be gone until this evening.

**Comment by visualizersdotnl** [comment]
The current LFO needs a new, simpler, design. Closing this ticket.
