### ISSUE TITLE
Possible options to approach modulating w/harmonically rich oscillators (as asked on Facebook)

### ISSUE THREAD

**Issue by visualizersdotnl** [bipolaraudio/FM-BISON#87]
Question, verbatim:

"I guess I don't expect an answer but as I've got enough musically inclined in my friend list, let's try to ask this question. 

Here's the situation: my FM synthesizer has many basic waveforms to pick from as an oscillator to use for each FM operator. However, if you modulate a sine wave (or anything) with a harmonically rich waveform such as a saw wave this will almost always result in a noisy/glitchy result you're probably not looking for. The solution is easy: right next to the waveform selection you select for example a low pass filter (each operator has it's own selection of 12dB filters) and "take the top off" (cut off the higher frequencies). You then end up with a shape that, to your liking, can very well be used as a modulator.

Before you ask: all relevant oscillators are band-limited when not used as LFO (and even then I secretly take the edge off the hardest discontinuities).

I'm not sure if I should be a purist here and expect my users to go about it like I described (advanced users, as this is about the R&D plug-in which we are actually transforming into a production grade tool - but not one we directly aim to sell), *or*:

A - Offer a toggle which shaves off the top off of all waveforms to the point they're always directly useful as a modulator. This would make them sound dull when used as carrier, i.e. not the *output* sound you're looking for when using said oscillator. 
B - Figure out if the operator in question is *only* used as a modulator (I can do that by checking if it's not a carrier operator (carrier in FM land means 'mix directly with voice output')) and do so automatically.
C - Leave it like it is, put a hint in the manual and expect people to be smart enough to get why things sound like they do 1:1."

@paulcoops - What do you think?

**Comment by visualizersdotnl** [comment]
Our friends at Majella opted to *always* lowpass FM modulation input a little. This makes a lot of sense since you're never looking for "full glitch" and if you do you really don't want to do it this way.

**Comment by paulcoops** [comment]
To be honest, for an internal R&D tool I don't see the need if we can already take a bit off the top using the OP filter. And I would go for C. 

As for always lowpass, I'm not so sure if this is a smart move for the engine, maybe we want full glitch to create *unheard* futuristic car engine sounds.

**Comment by visualizersdotnl** [comment]
I'm satisfied with this option. Closing issue.
